version: "3"
services:
  database:
    build: /db_docker
    environment:
     - MYSQL_ROOT_PASSWORD=swarup
    ports:
     - "3306:3306"
  web:
    build: .
    ports:
     - "8009:8080"
    links:
     - database
    
    
