version: '3'

services:
  mysqldb:
    build: ./db_docker
    container_name: mysqldb
    environment:
     - MYSQL_ROOT_PASSWORD=root
    
    ports:
     - '3306:3306'

    networks:
     - login-network
  web:
    build: .
    ports:
     - '8088:8080'
    container_name: login-page
    links:
     - mysqldb:3306

    networks:
     - login-network
    
networks:
  login-network:    

    
    
