version: '2.0'
services:
  database:
    build: ./db_docker
    environment:
     - MYSQL_ROOT_PASSWORD=swarup
    ports:
     - '3306:3306'
  web:
    build: .
    ports:
     - '8088:8080'
    links:
     - database
    
    
